### ISSUE TITLE
[Fabric 1.20.4] Console Spam Error

### ISSUE THREAD

**Issue by sciguyryan** [YUNG-GANG/YUNGs-Better-Jungle-Temples#6]
Hi!

Since updating to the latest version () at the time of writing, I keep seeing this error spamming my server console. I don't understand why since this is just an update, I haven't added or removed anything associated with the mod:

[08:42:43] [c2me-prioritized-0/ERROR]: Failed to get element ResourceKey[minecraft:worldgen/processor_list / bettertemples:taiga/main]
[08:42:43] [c2me-prioritized-0/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.class_3790.method_35448(class_3790.java:55) ~[server-intermediary.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.class_3790.<init>(class_3790.java:55) ~[server-intermediary.jar:?]
        at net.minecraft.class_6624.method_38711(class_6624.java:73) ~[server-intermediary.jar:?]
        at net.minecraft.class_3449.method_41621(class_3449.java:67) ~[server-intermediary.jar:?]
        at net.minecraft.class_2852.method_12392(class_2852.java:460) ~[server-intermediary.jar:?]
        at net.minecraft.class_2852.method_12395(class_2852.java:204) ~[server-intermediary.jar:?]
        at net.minecraft.class_3898.mdec244a$c2me-threading-chunkio$lambda$c2me$loadChunk0$5$1e(class_3898.java:14515) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at com.ishland.c2me.base.common.scheduler.WrappingTask.run(WrappingTask.java:21) ~[c2me-base-0.2.0+alpha.11.67-c13d8242d267c06b.jar:?]
        at com.ishland.flowsched.executor.WorkerThread.pollTasks(WorkerThread.java:56) ~[c2me-base-0.2.0+alpha.11.67-c13d8242d267c06b.jar:?]
        at com.ishland.flowsched.executor.WorkerThread.run(WorkerThread.java:27) ~[c2me-base-0.2.0+alpha.11.67-c13d8242d267c06b.jar:?]
        
 Can you give me any advise on what I need to do to resolve this? As far as I can see it's specific to bettertemples and none of your other mods (though also updated) are flagging up any errors. Very weird.

**Comment by yungnickyoung** [comment]
I'm not sure what mod that is, but "bettertemples" is not actually this mod. This mod's ID is `betterjungletemples`
